name: APK_Uretici
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g cordova
      - run: |
          cordova create build-app com.atolye.takip Atolye
          cd build-app
          cordova platform add android
          rm -rf www/*
          cp ../index.html www/
          cordova build android --debug
      - uses: actions/upload-artifact@v3
        with:
          name: Atolye-Uygulamasi-APK
          path: build-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
